call action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,65 +14,76 @@ env:
   PYTHON_VERSION: 3.8
 
 jobs:
-  test:
+  docs:
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.8]
     steps:
-      - name: 🛫 Checkout
-        uses: actions/checkout@v3
-
-      - name: 🐍 Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
+      - uses: actions/checkout@v4
+      - id: foo
+        uses: actions/codeforlife-action-docs@v0.1
         with:
-          python-version: ${{ matrix.python-version }}
+          who-to-greet: 'Mona the Octocat'
+      - run: echo random-number ${{ steps.foo.outputs.random-number }}
+        shell: bash
 
-      - name: 🛠 Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install pipenv
-          pipenv install --dev
+  # test:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.8]
+  #   steps:
+  #     - name: 🛫 Checkout
+  #       uses: actions/checkout@v3
 
-      - name: 🔎 Check Code Format
-        run: if ! pipenv run black --check .; then exit 1; fi
+  #     - name: 🐍 Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
 
-      - name: 🔎 Check Migrations
-        run: pipenv run python manage.py makemigrations --check --dry-run
+  #     - name: 🛠 Install Dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         python -m pip install pipenv
+  #         pipenv install --dev
 
-      # TODO: assert code coverage target.
-      - name: 🧪 Test Code Units
-        run: pipenv run pytest
+  #     - name: 🔎 Check Code Format
+  #       run: if ! pipenv run black --check .; then exit 1; fi
 
-  release:
-    concurrency: release
-    runs-on: ubuntu-latest
-    needs: [test]
-    if: github.ref_name == 'main'
-    steps:
-      - name: 🛫 Checkout
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          fetch-depth: 0
+  #     - name: 🔎 Check Migrations
+  #       run: pipenv run python manage.py makemigrations --check --dry-run
 
-      - name: 🐍 Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
+  #     # TODO: assert code coverage target.
+  #     - name: 🧪 Test Code Units
+  #       run: pipenv run pytest
 
-      - name: 🛠 Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install python-semantic-release~=7.33
+  # release:
+  #   concurrency: release
+  #   runs-on: ubuntu-latest
+  #   needs: [test]
+  #   if: github.ref_name == 'main'
+  #   steps:
+  #     - name: 🛫 Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         fetch-depth: 0
 
-      - name: ⚙️ Configure Git
-        run: |
-          git config --local user.name cfl-bot
-          git config --local user.email codeforlife-bot@ocado.com
+  #     - name: 🐍 Set up Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: 🚀 Publish Semantic Release
-        env:
-          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-        run: semantic-release publish --verbosity=INFO
+  #     - name: 🛠 Install Dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         python -m pip install python-semantic-release~=7.33
+
+  #     - name: ⚙️ Configure Git
+  #       run: |
+  #         git config --local user.name cfl-bot
+  #         git config --local user.email codeforlife-bot@ocado.com
+
+  #     - name: 🚀 Publish Semantic Release
+  #       env:
+  #         GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #       run: semantic-release publish --verbosity=INFO
